In [189]:
%matplotlib inline
import numpy as np
import pandas as pd
%matplotlib inline


np.random.seed(29)


In [280]:
double_rolls = np.random.choice([1,2,3,4,5,6], size = (100000, 2))
double_rolls

array([[6, 6],
       [6, 6],
       [5, 6],
       ...,
       [6, 3],
       [4, 4],
       [5, 3]])

In [281]:
double_rolls[:,0]

array([6, 6, 5, ..., 6, 4, 5])

In [282]:
wins = double_rolls[:,0] == double_rolls[:,1]
wins

array([ True,  True, False, ..., False,  True, False])

In [283]:
win_rate = wins.astype(int).mean()
win_rate


0.16573

In [284]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? 
#What is the probability of getting more than 3 heads?

# 0 = tails, 1 = heads
flips = np.random.choice([0, 1], size = (100000, 8))
flips

array([[0, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1]])

In [285]:
coin_flips.sum(axis=1)

array([4, 5, 3, ..., 4, 5, 3])

In [286]:

(coin_flips.sum(axis=1) == 3).mean()

0.22103

In [287]:
(coin_flips.sum(axis=1) > 3).mean()

0.63497

In [288]:
#There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
#Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds 
#that the two billboards I drive past both have data science students on them?

# WD = 0, DS = 1
billboard = np.random.choice([0, 1], size = (100000, 2), p = [0.75, 0.25])
billboard

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [0, 0]])

In [291]:
p = (billboard.sum(axis = 1) == 2).mean()
p

0.06185

In [120]:
#Codeup students buy, on average, 3 poptart packages with a standard deviation of 
#1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 
#poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 
#(Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a 
#judgement call on how to handle some of your values



poptart = np.random.normal(3,1.5, size = (10000, 5))

poptart

array([[ 1.0773031 ,  2.15288804,  1.82705605,  0.82291784,  4.78212337],
       [ 2.82667484,  2.79884196,  3.32284829,  3.96905463,  5.55856982],
       [ 3.72250074,  4.94110698,  3.91351927,  3.27711951,  4.99622207],
       ...,
       [ 4.24385638,  5.04471439,  4.94662913,  5.30394435,  2.68190644],
       [ 1.49602628,  2.18941501,  3.3858733 ,  2.71152539,  1.10941266],
       [ 4.96843477,  2.9182412 ,  6.54294494, -1.99972435,  3.2974411 ]])

In [121]:
poptart.sum(axis=1)

array([10.6622884 , 18.47598954, 20.85046856, ..., 22.2210507 ,
       10.89225265, 15.72733766])

In [295]:
poptart.sum(axis=1) <= 16

array([ True, False, False, ..., False,  True,  True])

In [294]:
# poptart.sum(axis=1) >= 16 to get booleans

(poptart.sum(axis=1) <= 16).mean()

0.6089

In [127]:
#Compare Heights

#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, standard d = 6cm.
#Since you have means and standard deviations, you can use np.random.normal to generate observations.
#If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?



men_heights = np.random.normal(178,8, size = (10000))
                               
women_heights = np.random.normal(170,6, size = (10000))


In [139]:
men_heights

array([175.79579371, 169.40524445, 182.14506047, ..., 180.92553036,
       183.50337037, 186.85451021])

In [140]:
#pd.DataFrame(women_heights)

women_heights

array([169.67790225, 174.33674533, 175.82048126, ..., 177.22471648,
       173.02263328, 179.44582128])

In [146]:
pd.DataFrame(women_heights).describe()

0
count  10000.000000
mean     170.024493
std        6.024616
min      146.741771
25%      165.899170
50%      170.050447
75%      174.190008
max      191.668009

In [147]:
pd.DataFrame(men_heights).describe()

0
count  10000.000000
mean     178.203175
std        8.038510
min      142.974222
25%      172.799259
50%      178.239617
75%      183.619373
max      210.886376

In [296]:
(women_heights > men_heights).mean()

0.2101

In [300]:
#When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
#and the installation fails. What are the odds that after having 50 students download anaconda, 
#no one has an installation issue? 100 students?

#What is the probability that we observe an installation issue within the first 150 students 
#that download anaconda?


# 0 = no issues, 1 = issue
corrupt50 = np.random.choice([0,1], size = (10000, 50), p = [249/250, 1/250])
corrupt50


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [301]:
# no issues for 50 students
(corrupt50.sum(axis = 1) == 0).mean()

0.8181

In [302]:
corrupt100 = np.random.choice([0,1], size = (10000, 100), p = [249/250, 1/250])
corrupt100

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [303]:
(corrupt100.sum(axis = 1) == 0).mean()

0.672

In [304]:
corrupt150 = np.random.choice([0,1], size = (10000, 150), p = [249/250, 1/250])
corrupt150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [305]:
(corrupt150.sum(axis = 1) == 0).mean()

0.5432

In [306]:
corrupt450 = np.random.choice([0,1], size = (10000, 450), p = [249/250, 1/250])
corrupt150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [307]:
(corrupt450.sum(axis = 1) == 0).mean()

0.1643

In [308]:
#There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
#However, you haven't seen a food truck there in 3 days. How unlikely is this?
#How likely is it that a food truck will show up sometime this week?


# 0 = np truck, 1 = truck shows up
food_truck = np.random.choice([0, 1], size = (10000, 3), p = [0.3, 0.7] )
food_truck

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 1],
       ...,
       [1, 0, 1],
       [1, 1, 1],
       [1, 0, 1]])

In [309]:
(food_truck.sum(axis = 1) == 0).mean()

0.0265

In [310]:
food_truck_week = np.random.choice([0, 1], size = (10000, 5), p = [0.3, 0.7] )
food_truck_week

array([[1, 1, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1],
       ...,
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1]])

In [312]:
(food_truck_week.sum(axis = 1) > 1).mean()

0.9715

In [274]:
#If 23 people are in the same room, what are the odds that two of them share a birthday? 
#What if it's 20 people? 40?


bday = np.random.choice(range(1,366), size = (10000, 23))
bday


array([[ 42, 249,  84, ..., 117,  12, 278],
       [ 20, 331, 296, ..., 273, 319, 247],
       [ 10,   9, 181, ...,  97, 250, 175],
       ...,
       [246, 233, 140, ..., 246,  37, 106],
       [296, 136, 232, ..., 239, 248, 325],
       [136,  77, 353, ..., 210,  54, 223]])

In [278]:
pd.DataFrame(bday)

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      42  249   84  263  329  170  116  226  159   19  ...  238  151   82   
1      20  331  296  311  267  224  130  133    7   94  ...  198  193  304   
2      10    9  181  203   81   41   79  220  172   98  ...  241  312   11   
3     189  116   32  316  284   83  164  347  274   78  ...  234    6   56   
4      62   53  359  195  333    5  286  299    9   55  ...   22   18  218   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  208  218  217  270  158   99   91  319  212  165  ...  219   74  152   
9996  284  361   68  202  240  312  194  274  121  162  ...   57  238   41   
9997  246  233  140  208  223  104  223  112  130  140  ...  149  347  126   
9998  296  136  232  286  238  321   46   25   35   13  ...  178  359  365   
9999  136   77  353  206  202  326  114  239  362  131  ...   31  132   13   

       16   17   18   19   20   21   22  
0      78  309  329  280  117   12  278  
1      38   92  181  235  273  319  247  
2     347  134  292  188   97  250  175  
3     102  312  190  175  204  263  118  
4      28    4  122  274  165   16  310  
...   ...  ...  ...  ...  ...  ...  ...  
9995  143  365  338  192   97  338  257  
9996  158  344   55  197  328   28  132  
9997  166   46  154  361  246   37  106  
9998   88  260  140  118  239  248  325  
9999  253   96  195  333  210   54  223  

[10000 rows x 23 columns]

In [279]:
pd.DataFrame(bday).nunique(axis = 1)

0       22
1       23
2       23
3       23
4       23
        ..
9995    22
9996    23
9997    20
9998    22
9999    22
Length: 10000, dtype: int64

In [276]:
(pd.DataFrame(bday).nunique(axis = 1) < 23).mean()

0.5097

In [313]:
n_simulations = 100_000
n_people = 20


birthdays = np.random.choice(range(365), size=(n_simulations, n_people))
df = pd.DataFrame(birthdays)
df["n_unique"] = df.nunique(axis=1)
(df.n_unique != n_people).mean()

0.41025

In [314]:
n_simulations = 100_000
n_people = 40


birthdays = np.random.choice(range(365), size=(n_simulations, n_people))
df = pd.DataFrame(birthdays)
df["n_unique"] = df.nunique(axis=1)
(df.n_unique != n_people).mean()

0.89227